/**
 * Prebuild script: reads .env and generates electron/config.js with hardcoded values.
 * Run before packaging so no .env file is needed at runtime.
 */

import dotenv from "dotenv";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

dotenv.config({ path: path.resolve(__dirname, "../.env") });

const config = `// AUTO-GENERATED by scripts/generate-config.js — do not edit manually
export const config = {
	API_URL: "${process.env.VITE_API_URL || "http://localhost:5000/api/v1"}",
	GOOGLE_CLIENT_ID: "${process.env.GOOGLE_CLIENT_ID || ""}",
	GOOGLE_CLIENT_SECRET: "${process.env.GOOGLE_CLIENT_SECRET || ""}",
	SUMMARY_MAX_TOKENS: ${parseInt(process.env.VITE_SUMMARY_MAX_TOKENS) || 800},
	SUMMARY_TOKEN_THRESHOLD: ${parseInt(process.env.VITE_SUMMARY_TOKEN_THRESHOLD) || 1500},
};
`;

const outPath = path.resolve(__dirname, "../electron/config.js");
fs.writeFileSync(outPath, config, "utf-8");
console.log("✅ electron/config.js generated from .env");
